### ISSUE TITLE
ROMS head of develop fails in build

### ISSUE THREAD

**Issue by uturuncoglu** [oceanmodeling/roms#6]
ROMS head of develop is failing when it is compiled under UFS Coastal. It is tested on Hercules with Intel compiler. 

Here is the error log,

```
Found Python: /apps/spack-managed/gcc-11.3.1/miniconda3-24.3.0-avnaftwsbozuvtsq7jrmpmcvf6c7yzlt/bin/python3
CMake Error at ROMS-interface/ROMS/Compilers/roms_functions.cmake:25 (find_program):
  Could not find CPP_CLEAN using the following names: cpp_clean
Call Stack (most recent call first):
  ROMS-interface/ROMS/CMakeLists.txt:71 (include)
```

**Comment by uturuncoglu** [comment]
@hga007 JFYI, I created an issue about build to track it. Probably, I'll fixed it soon.

**Comment by uturuncoglu** [comment]
Closing this issue wide head of develop works without any issue.

**Comment by hga007** [comment]
@uturuncoglu: I need to check why the UFS is blowing up for me. I haven't done anything for a while. I also want to merge **`feature/stdinp`** into **`develop`**, but I wanted to ask you first. I have a couple of PRs that I also want to merge.

**Comment by uturuncoglu** [comment]
@hga007 I have just wrote you about `feature/stdinp` under other issue.

**Comment by uturuncoglu** [comment]
@hga007 FYI, https://github.com/oceanmodeling/roms/issues/2
